version = 0.1

[default.deploy.parameters]
stack_name = "iris-prod"
resolve_s3 = true
s3_prefix = "iris-prod"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = []

[default.global.parameters]
region = "us-east-1"

[infra.deploy.parameters]
template_file = "infra.yaml"
stack_name = "iris-infra-prod"
resolve_s3 = true
s3_prefix = "iris-infra-prod"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
no_execute_changeset = false
parameter_overrides = "Stage=prod"
image_repositories = []

[app.deploy.parameters]
template_file = "app.yaml"
stack_name = "iris-app-prod"
resolve_s3 = true
s3_prefix = "iris-app-prod"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "Stage=prod InfraStackName=iris-infra-prod ReminderDelaySeconds=60 ContactToEmail=eugene.yamnitsky@gmail.com ContactFromEmail=no-reply@liazon.cc AllowedOrigins=https://liazon.cc,https://www.liazon.cc SesRegion=us-east-1 ContactApiId=7ofigcp921"
image_repositories = []
